server:
  port: ${PORT:8090}


spring:
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:mariadb.twolinecode.com}:${DB_PORT:3306}/${DB_DATABASE:digital-lab}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=${DB_SSL_USE:false}&disableSslHostnameVerification=${DISABLE_SSL_HOSTNAME_VERIFICATION:false}
    username: ${DB_USERNAME:dlab}
    password: ${DB_PASSWORD:digital1234$#@!}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: 1234
  redis:
    host: localhost
    port: 6379

mybatis:
  type-aliases-package: com.shop.domain.model
  mapper-locations: mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

JwtProperties:
  token-prefix: Authorization